### ISSUE TITLE
A Small Question

### ISSUE THREAD

**Issue by engineeringstudent0012** [gane-detoxx/image-encryption#1]
Thank You For The Code.I really appreciate it from the bottom of my heart.
Can you tell which algorithm is used in the image encryption and decryption.Is it CBC algorithm?
Thank You for the code again

**Comment by gane-detoxx** [comment]
I'm soo glad to hear that it helped you and about that algorithm, me and @jnth-glitch came up with that. if you have any doubts feel free to dm me and don't raise it as an issue
